server:
  port: 9090
spring:
  application:
    name: Microservicios-ApiG
  cloud:
    gateway:
      routes:
        - id: ROUTE-USER
          uri: http://localhost:9090
          predicates:
            - Path=/user/create/**
        - id: ROUT-ACCOUNT
          uri: http://localhost:9090
          predicates:
            - Path=/account/create/**
  datasource:
      url: jdbc:mariadb://localhost:3307/bank_lite?useSSL=false&serverTimezone=UTC
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: Password1*.
  jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MariaDBDialect
        hibernate:
          ddl-auto: update